image_width: 2048
image_height: 1536
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1750.968903, 0.000000, 1075.905454, 0.000000, 1743.615856, 752.604198, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.021089, -0.009644, -0.011353, 0.000018, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1743.657593, 0.000000, 1077.059548, 0.000000, 0.000000, 1733.886597, 740.643734, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
