image_width: 2048
image_height: 1536
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1747.199180, 0.000000, 1034.043018, 0.000000, 1758.915741, 741.523992, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.008416, -0.064561, -0.003459, -0.001223, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1739.363403, 0.000000, 1032.011867, 0.000000, 0.000000, 1757.097778, 737.783887, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
